baseURL = 'https://easytae.github.io/gilog'
languageCode = 'ko-kr'
title = '기록'
theme = 'm10c'

# enableGitInfo = true

[params]
  images = ['img/profile.webp', 'img/profile.png']
  title = '기록'
  description = 'no time to be busy'