baseURL = 'https://easytae.github.io/gilog'
languageCode = 'ko-kr'
title = '기록'
theme = 'm10c'

# enableGitInfo = true

[params]
  images = ['profile.webp']
  title = '기록'
  description = 'Text about my cool site'