baseURL: 'http://localhost:1313/'
#baseURL: 'https://easytae.github.io/devlog/'
languageCode: 'ko-kr'
title: 'DevLog'
theme: 'm10c'

taxonomies:
  tag: 'tags'

params:
  images: [ 'img/profile.webp', 'img/profile.png' ]
  author: 'Lee Ji-Tae'
  title: 'DevLog'
  description: 'no time to be busy'